version: "3.8"
services: 
  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - "8080:8080"
    depends_on:
      - backend
    volumes:
      - ./frontend:/app 
      - /app/node_modules
  
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    depends_on:
      - redis
    environment:
      - OLLAMA_HOST=http://ollama:11434
  
  worker:
    build: ./celery_worker
    volumes:
      - ./celery_worker:/tasks
    depends_on:
      - redis
    environment:
      - OLLAMA_HOST=http://ollama:11434
  
  redis:
    image: redis:7
    ports:
      - "6379:6379"
  
  ollama:
    image: ollama/ollama
    ports:
      - "11434:11434"
    environment:
      - OLLAMA_METAL=1
      - OLLAMA_CONTEXT_LENGTH=65536
    volumes:
      - ollama_data:/root/.ollama
    deploy: {} 
    runtime: nvidia

  flower:
    image: mher/flower
    ports:
      - "5555:5555"
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
    depends_on:
      - redis

volumes:
  ollama_data: